/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        terra: {
          100: '#FDF0EB',
          200: '#F6D0C0',
          300: '#E8A080',
          400: '#D4714A',
          500: '#C0522A',
          600: '#A03E1C',
          700: '#7D2E11',
          800: '#5A1F08',
          900: '#3A1105',
        },
        gold: {
          100: '#FEF9EC',
          200: '#FAE8A8',
          300: '#F5D468',
          400: '#E8B83A',
          500: '#D4A017',
          600: '#A87C10',
          700: '#7C5A08',
        },
        ink: {
          100: '#3D2B14',
          200: '#2C1F10',
          300: '#1F1509',
          400: '#1A1008',
          500: '#120B05',
        },
      },
      fontFamily: {
        yeseva: ["'Yeseva One'", 'serif'],
        cormorant: ["'Cormorant Garamond'", 'serif'],
        sans: ["'DM Sans'", 'sans-serif'],
        mono: ["'IBM Plex Mono'", 'monospace'],
        tiro: ["'Tiro Devanagari'", 'serif'],
      },
      animation: {
        'fade-up': 'fadeUp 0.6s var(--ease-out-expo) both',
        'fade-down': 'fadeDown 0.4s var(--ease-out-expo) both',
        'fade-left': 'fadeLeft 0.6s var(--ease-out-expo) both',
        'fade-right': 'fadeRight 0.6s var(--ease-out-expo) both',
        'scale-up': 'scaleUp 0.5s var(--ease-out-expo) both',
        'clip-reveal': 'clipReveal 0.8s var(--ease-out-expo) both',
        'pulse-ring': 'pulseRing 2s ease-out infinite',
        'breathe': 'breathe 5s ease-in-out infinite',
        'float-y': 'floatY 7s ease-in-out infinite',
        'shimmer': 'shimmer 1.5s infinite',
        'spin-slow': 'spinSlow 3s linear infinite',
        'marquee': 'marquee 25s linear infinite',
        'confetti': 'confetti 1.2s ease forwards',
        'slide-panel': 'slideInPanel 0.45s cubic-bezier(0.16,1,0.3,1) both',
      },
      transitionTimingFunction: {
        'out-expo': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'in-expo': 'cubic-bezier(0.7, 0, 0.84, 0)',
        'spring': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        'bounce': 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
        'smooth': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'sharp': 'cubic-bezier(0.4, 0, 0.6, 1)',
      },
      spacing: {
        '18': '4.5rem',
        '22': '5.5rem',
        '26': '6.5rem',
        '30': '7.5rem',
      },
      maxWidth: {
        'content': '1380px',
      },
      zIndex: {
        'below': '-1',
        'raised': '10',
        'sticky': '200',
        'overlay': '300',
        'modal': '400',
        'toast': '500',
        'cursor': '9999',
      },
    },
  },
  plugins: [],
};
